name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 17 ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4.2.1
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          architecture: x64

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.5.0

      - name: Cache Gradle Packages
        uses: actions/cache@v4.0.2
        with:
          path: |
            ~/RedisBungee-Plugin/.gradle/caches
            ~/RedisBungee-Plugin/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/RedisBungee-Plugin/*.gradle*', '**/RedisBungee-Plugin/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          ./redisbungee build